twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        categoryNewsRepository: "@App\\Repository\\CategoryNewsRepository"
        actualityNewsRepository: "@App\\Repository\\ActualityNewsRepository"
        topicRepository: "@App\\Repository\\TopicRepository"
        videoRepository: "@App\\Repository\\VideoRepository"

when@test:
    twig:
        strict_variables: true
